# Generated by Django 5.2 on 2025-09-11 13:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=50)),
                ('phone', models.TextField()),
                ('password', models.CharField(max_length=50)),
                ('certificate', models.FileField(upload_to='certificates/')),
                ('date', models.DateField(default=datetime.date.today)),
            ],
        ),
    ]
