# Generated by Django 5.2 on 2025-09-12 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0003_alter_register_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='register',
            old_name='date',
            new_name='registered_on',
        ),
        migrations.RemoveField(
            model_name='register',
            name='certificate',
        ),
        migrations.RemoveField(
            model_name='register',
            name='certificate_hash',
        ),
        migrations.RemoveField(
            model_name='register',
            name='password',
        ),
        migrations.RemoveField(
            model_name='register',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='register',
            name='user',
        ),
    ]
