# Generated by Django 5.2 on 2025-09-12 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0004_rename_date_register_registered_on_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='register',
            old_name='registered_on',
            new_name='date',
        ),
        migrations.AddField(
            model_name='register',
            name='certificate',
            field=models.FileField(blank=True, null=True, upload_to='certificates/'),
        ),
        migrations.AddField(
            model_name='register',
            name='name',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='register',
            name='password',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='register',
            name='phone',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='register',
            name='username',
            field=models.CharField(default='', max_length=50),
        ),
    ]
