# Generated by Django 5.2 on 2025-09-12 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0005_rename_registered_on_register_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='certificate_hash',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
